### ISSUE TITLE
Header appears when focusing text boxes

### ISSUE THREAD

**Issue by Spencer-Smith** [Spencer-Smith/tickets#45]
The blue "client" header is not visible until the user focuses on a text box. However, ideally it would not appear at all.

Steps to reproduce:
1. Start app
2. Focus any text box such as "username" or "password"
3. Leave the text box. The header will now be visible at the top of the page

Intended function/fix:
Because our app makes use of the entire screen and the header doesn't fit the style, the header should not show up at all.

**Comment by derekmines** [comment]
One of our commits fixed this, but I don't remember which one. Anyways, it's fixed now.
